---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_license: accept
  product_name: chef
  product_version: <%= ENV['KITCHEN_CHEF_VERSION'] || ENV['CHEF_VERSION'] || 'latest' %>
  client_rb:
    ohai.directory: /tmp/kitchen/ohai/cookbook_plugins

verifier:
  name: inspec

platforms:
- name: debian-9.5
  run_list:
    - recipe[apt]

suites:
  - name: python2
    run_list:
      - recipe[spython::2]
    attributes:
      spython:
        "2":
          pip_packages:
            click: null
            PyYAML: 3.13
    verifier:
      inspec_tests:
        - path: test/integration/default
      inputs:
        runtime: "2"
        pip_bin: pip2
        packages:
          click: null
          PyYAML: 3.13
  - name: python3
    run_list:
      - recipe[spython::3]
    attributes:
      spython:
        "3":
          pip_packages:
            click: null
            PyYAML: 3.13
    verifier:
      inspec_tests:
        - path: test/integration/default
      inputs:
        runtime: "3"
        pip_bin: pip3
        packages:
          click: null
          PyYAML: 3.13
