---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero
  chef_license: accept
  product_name: chef
  product_version: <%= ENV['KITCHEN_CHEF_VERSION'] || ENV['CHEF_VERSION'] || 'latest' %>
  client_rb:
    ohai.directory: /tmp/kitchen/ohai/cookbook_plugins

verifier:
  name: inspec

platforms:
  - name: debian-9
    run_list:
      - recipe[apt]
  - name: debian-10
    run_list:
      - recipe[apt]
  - name: debian-bullseye
    run_list:
      - recipe[apt]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]
      - recipe[locales]
  - name: ubuntu-18.04
    run_list:
      - recipe[apt]
  - name: centos-7
    run_list:
      - recipe[yum-epel]
    attributes:
      spython:
        "2":
          pip_upgrade: "==20.3.4"
          setuptools_upgrade: true
        "3":
          pip_upgrade: "==20.3.4"
    verifier:
      inputs:
        packages:
          pip: "20.3.4"

suites:
  - name: python2
    excludes:
      - debian-bullseye
      - ubuntu-18.04
    run_list:
      - recipe[spython::2]
    attributes:
      spython:
        "2":
          pip_packages:
            click: null
            PyYAML: 3.13
    verifier:
      inspec_tests:
        - path: test/integration/default
      inputs:
        runtime: "2"
        pip_bin: pip2
        packages:
          click: null
          PyYAML: 3.13
  - name: python3
    run_list:
      - recipe[spython::3]
    attributes:
      spython:
        "3":
          pip_packages:
            click: null
            PyYAML: 3.13
    verifier:
      inspec_tests:
        - path: test/integration/default
      inputs:
        runtime: "3"
        pip_bin: pip3
        packages:
          click: null
          PyYAML: 3.13
